### PR TITLE
NumberType as struct, include netstandard2.1 version in the package

### PR DESCRIPTION
**Pull request by Thorium**

### CODE REVIEW

**Comment by ChrSteinert** [comment]
This is the first PR I received ever – so, thank you! :)

**Comment by Thorium** [comment]
This is way under-rated component, it should be part of F# tooling itself and available from debugger view.

**Comment by ChrSteinert** [comment]
The new NuGet is currently validating.

**Comment by Thorium** [comment]
Maybe rendering them with dotnet interactive notebooks could be easy way to enhance the availability: https://github.com/dotnet/interactive/blob/main/docs/formatting.md#replacing-the-default-formatting-for-a-type

**Comment by Thorium** [comment]
Here seems to be an F# suggestion: https://github.com/dotnet/fsharp/issues/17071

**Comment by ChrSteinert** [comment]
Oh wow – I was not aware of this. Thanks for letting me know!

**Pull request merged**
